// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZHlGAoy8SN6Fxuz0DCdABrZMZoSWGgo',
    appId: '1:586497987416:web:2f1a63db0c2816e5fecb2d',
    messagingSenderId: '586497987416',
    projectId: 'task-mate-4596c',
    authDomain: 'task-mate-4596c.firebaseapp.com',
    storageBucket: 'task-mate-4596c.firebasestorage.app',
    measurementId: 'G-MBJ474310K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHCkcpIQDNHvL0GGoOx0eGYR7eZqpQfc',
    appId: '1:586497987416:android:b7febff9a2b08a06fecb2d',
    messagingSenderId: '586497987416',
    projectId: 'task-mate-4596c',
    storageBucket: 'task-mate-4596c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxnYQVHZBoT2xF_x9EqEw7e1JbwjQYzk',
    appId: '1:586497987416:ios:e1ba327c439072b7fecb2d',
    messagingSenderId: '586497987416',
    projectId: 'task-mate-4596c',
    storageBucket: 'task-mate-4596c.firebasestorage.app',
    iosBundleId: 'com.example.taskMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSxnYQVHZBoT2xF_x9EqEw7e1JbwjQYzk',
    appId: '1:586497987416:ios:e1ba327c439072b7fecb2d',
    messagingSenderId: '586497987416',
    projectId: 'task-mate-4596c',
    storageBucket: 'task-mate-4596c.firebasestorage.app',
    iosBundleId: 'com.example.taskMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZHlGAoy8SN6Fxuz0DCdABrZMZoSWGgo',
    appId: '1:586497987416:web:db32407953a768e1fecb2d',
    messagingSenderId: '586497987416',
    projectId: 'task-mate-4596c',
    authDomain: 'task-mate-4596c.firebaseapp.com',
    storageBucket: 'task-mate-4596c.firebasestorage.app',
    measurementId: 'G-PPT409FC3J',
  );
}
